= RESTful Bid-Statistics API Guide
xplorist <hzcd-mis-sys4@mail.foxconn.com>
v0.0.1 2020-03-26
:toc: left
:toclevels: 3
:toc-title: 目  录
:doctype: book
:icons: font
:operation-curl-request-title: Curl 请求
:operation-httpie-request-title: HTTPie 请求
:operation-http-request-title: Http 请求
:operation-request-parameters-title: 请求参数说明
:operation-request-fields-title: 请求参数说明
:operation-http-response-title: Http 响应
:operation-response-fields-title: Http 响应字段说明
:operation-links-title: 相关链接

[[overview]]
== 1、概要
本文为API说明文档。

API 分两部分，一部分为完全的 RESTFul 风格的 API ，另一部分为普通的 API

API的说明包括：请求方式、请求地址、请求参数说明和响应消息等。

[[overview-response]]
== 2、通用说明

*非 RESTFul API 通用响应消息说明*

|===
| 字段 | 类型 | 解释

| code
| String
| 1为成功，0为失败，其他为自定义状态

| msg
| String
| 响应附带的消息

| t
| Object
| 请求的数据
|===

[[resources]]
== 3、RESTFul API

[[resources-a00]]
=== 项目网关地址：http://10.244.231.103:14000/bid-forum

[[resources-a00-b01]]
=== 前端请求格式:/bid/api/bid-forum

[[resources-a01]]
=== 【01】发帖（需要token）

*前端请求格式:/bid/api/bid-forum*

operation::send-post[snippets='request-fields,http-request,response-fields,http-response']

[[resources-a02]]
=== 【02】分页查询所有帖子list

*前端请求格式:/bid/api/bid-forum*

operation::list-posts-by-page[snippets='request-parameters,http-request,response-fields,http-response']

[[resources-a03]]
=== 【03】回复帖子（需要token）

*前端请求格式:/bid/api/bid-forum*

operation::send-reply[snippets='request-fields,http-request,response-fields,http-response']

[[resources-a04]]
=== 【04】根据ID查询单个帖子

*前端请求格式:/bid/api/bid-forum*

operation::get-post-by-id[snippets='request-parameters,http-request,response-fields,http-response']

[[resources-a05]]
=== 【05】查询通知list

*前端请求格式:/bid/api/bid-forum*

operation::listNotice[snippets='request-parameters,http-request,response-fields,http-response']

[[resources-a06]]
=== 【06】删除单条通知(需要token)

*前端请求格式:/bid/api/bid-forum*

operation::deleteSingleNotice[snippets='request-parameters,http-request,response-fields,http-response']

[[resources-a07]]
=== 【07】一键删除当前用户的所有通知（需要token）

*前端请求格式:/bid/api/bid-forum*

operation::deleteAllNotice[snippets='http-request,response-fields,http-response']

[[resources-a08]]
=== 【08】删除帖子（需要token）

*前端请求格式:/bid/api/bid-forum*

operation::deletePost[snippets='request-parameters,http-request,response-fields,http-response']

[[resources-a09]]
=== 【09】删除回复（需要token）

*前端请求格式:/bid/api/bid-forum*

operation::deleteReply[snippets='request-parameters,http-request,response-fields,http-response']